version: '2'

services:
  pomelo:
    build: .
    ports:
      - "5000:80"
    volumes:
      - "./data:/data"
  node:
    image: node
    entrypoint: sleep 9999999
    volumes:
      - "./Frontend:/Frontend"
